import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Oxanium, Outfit, Lexend } from "next/font/google";
import { cn } from "@/lib/utils";
import "../globals.css";

const oxaniumHeading = Oxanium({ subsets: ["latin"], variable: "--font-heading" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const oxanium = Oxanium({
    subsets: ["latin"],
    variable: "--font-oxanium",
});

const outfit = Outfit({
    subsets: ["latin"],
    variable: "--font-outfit",
});

const lexend = Lexend({
    subsets: ["latin"],
    variable: "--font-lexend",
});

export const metadata: Metadata = {
    title: "VANI",
    description: "Generated by create next app",
};

export default function MinimalLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                oxanium.variable,
                lexend.variable,
                "font-sans",
                outfit.variable,
                oxaniumHeading.variable
            )}
        >
            <body className="min-h-full bg-[#080708]">{children}</body>
        </html>
    );
}
